const fs = require('fs')
const path = require('path')

const dirname = path.resolve()
const { version } = require(`${dirname}/package.json`)

const versionFileContents = `// THIS FILE WAS AUTOMATICALLY GENERATED by scripts/writeVersionFile.js
export const version = '${version}'
`

fs.writeFileSync(`${dirname}/tokens/version.ts`, versionFileContents)

console.log('tokens/version.ts updated to version', version)
